name: Docker Image CI

on:
  push:
    branches: [ "dev", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: ghcr.io/bbhmtech/joycoin:latest
          platforms: linux/amd64
          push: true
          cache-from: type=registry,ref=ghcr.io/bbhmtech/joycoin:latest
          cache-to: type=inline